no change     /home/agarwal.rishi/.conda/envs/ee/condabin/conda
no change     /home/agarwal.rishi/.conda/envs/ee/bin/conda
no change     /home/agarwal.rishi/.conda/envs/ee/bin/conda-env
no change     /home/agarwal.rishi/.conda/envs/ee/bin/activate
no change     /home/agarwal.rishi/.conda/envs/ee/bin/deactivate
no change     /home/agarwal.rishi/.conda/envs/ee/etc/profile.d/conda.sh
no change     /home/agarwal.rishi/.conda/envs/ee/etc/fish/conf.d/conda.fish
no change     /home/agarwal.rishi/.conda/envs/ee/shell/condabin/Conda.psm1
no change     /home/agarwal.rishi/.conda/envs/ee/shell/condabin/conda-hook.ps1
no change     /home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /home/agarwal.rishi/.conda/envs/ee/etc/profile.d/conda.csh
no change     /home/agarwal.rishi/.bashrc
No action taken.
Traceback (most recent call last):
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/data.py", line 330, in _execute_cloud_call
    return call.execute(num_retries=num_retries)
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 429 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/algorithms?prettyPrint=false&alt=json returned "Too Many Requests: Request was rejected because the request rate or concurrency limit was exceeded.". Details: "Too Many Requests: Request was rejected because the request rate or concurrency limit was exceeded.">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "step3_mine_detection.py", line 6, in <module>
    ee.Initialize()
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/__init__.py", line 125, in Initialize
    ApiFunction.initialize()
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/apifunction.py", line 154, in initialize
    signatures = data.getAlgorithms()
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/data.py", line 1063, in getAlgorithms
    return _cloud_api_utils.convert_algorithms(_execute_cloud_call(call))
  File "/home/agarwal.rishi/.conda/envs/ee/lib/python3.7/site-packages/ee/data.py", line 332, in _execute_cloud_call
    raise _translate_cloud_exception(e)
ee.ee_exception.EEException: Too Many Requests: Request was rejected because the request rate or concurrency limit was exceeded.
